DROP TABLE IF EXISTS CLIENT_SERVICE_DETAILS;  
DROP TABLE IF EXISTS NODE_INFO; 

CREATE TABLE CLIENT_SERVICE_DETAILS 
(
ID INT PRIMARY KEY NOT NULL,      
IP VARCHAR(50) NOT NULL,
PORT VARCHAR(50) NOT NULL,  
SERVICE_NAME VARCHAR(50) NOT NULL  
); 


CREATE TABLE NODE_INFO 
(   
NODE_NAME VARCHAR(50) PRIMARY KEY NOT NULL,  
IP VARCHAR(50) NOT NULL,
PORT VARCHAR(50) NOT NULL,  
STATUS VARCHAR(50) NOT NULL  
);  